[package]
name = "trigger-telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
contracts = { path = "../contracts" }
serde = { version = "1", features = ["derive"] }
teloxide = { version = "0.17", default-features = false, features = ["rustls"] }

[dev-dependencies]
serde_json = "1"
